# Generated by Django 2.0 on 2018-07-21 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_name', models.CharField(max_length=100, verbose_name='粉丝名称')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('nick_name', models.CharField(default='', max_length=20, verbose_name='昵称')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.CharField(max_length=254, verbose_name='邮箱')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('avatar', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='头像')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('last_login', models.DateTimeField(auto_now=True, null=True, verbose_name='最后登录')),
            ],
        ),
        migrations.AddField(
            model_name='userfollower',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='用户'),
        ),
    ]
