# Generated by Django 2.0 on 2018-08-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180725_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollower',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFollower',
        ),
    ]
